
name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller xlrd

      - name: Build with spec
        run: |
          pyinstaller app_exact.spec

      - name: Upload artifact (directory build)
        uses: actions/upload-artifact@v4
        with:
          name: hx-offline-editor-dist
          path: dist/**

      - name: Upload single EXE if exists
        uses: actions/upload-artifact@v4
        with:
          name: hx-offline-editor-exe
          path: dist/*.exe
          if-no-files-found: ignore
